### ISSUE TITLE
Add an option to list available sources

### ISSUE THREAD

**Issue by cktakahasi** [CESARBR/knot-modbus-source#3]
Extend test-sources adding new option to list registered sources

**Comment by BRDuarteSouza** [comment]
Sources are listed to a given slave path. Empty messages are displayed if no sources were found.

**Comment by ramonhpr** [comment]
Closed by: https://github.com/CESARBR/knot-modbus-source/commit/a3cb2102fedd8ec263d05f3d9c80d1eed1703ae0#diff-a7736f4f5ec946b4f7b3ff8cf37c6848
