### ISSUE TITLE
Create storage files/path based on slave random id

### ISSUE THREAD

**Issue by cktakahasi** [CESARBR/knot-modbus-source#6]
Slave id (random) should be used as path(directory) name at /var/lib/modbus/slave_id

Storage path suggestion:
if (test "${prefix}" = "NONE"); then
        dnl no prefix and no localstatedir, so default to /var
        if (test "$localstatedir" = '${prefix}/var'); then
                AC_SUBST([localstatedir], ['/var'])
        fi

        prefix="${ac_default_prefix}"
fi

if (test "$localstatedir" = '${prefix}/var'); then
        storagedir="${prefix}/var/lib/modbus"
else
        storagedir="${localstatedir}/lib/modbus"
fi
AC_DEFINE_UNQUOTED(STORAGEDIR, "${storagedir}",
                        [Directory for the storage files])

**Comment by ramonhpr** [comment]
Closed by this commit: https://github.com/CESARBR/knot-modbus-source/commit/805ad289a321b54a148fc80721b1023770762060#diff-67e997bcfdac55191033d57a16d1408a
